version: "3.9"

services:
  caddy:
    ports:
      - 80:80

  temporal-ui:
    image: temporalio/ui
    container_name: todo-app-temporal-ui
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal-ui.env
    networks:
      - todo-app
    depends_on:
      - temporal

  temporal-admin-tools:
    image: temporalio/admin-tools
    container_name: todo-app-temporal-admin-tools
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal-cli.env
    stdin_open: true
    tty: true
    networks:
      - todo-app
    depends_on:
      - temporal
