version: "3.9"

services:
  traefik:
    build: ./backend/traefik/prod
    deploy:
      restart_policy:
        condition: any
    ports:
      - 443:443
    secrets:
      - source: private.key
        target: /etc/traefik/certs/private.key
      - source: public.crt
        target: /etc/traefik/certs/public.crt

  # caddy:
  #   build: ./backend/caddy/prod
  #   deploy:
  #     restart_policy:
  #       condition: any
  #   ports:
  #     - 443:443
  #   secrets:
  #     - source: private.key
  #       target: /etc/caddy/certs/private.key
  #     - source: public.crt
  #       target: /etc/caddy/certs/public.crt

  todo-app:
    deploy:
      restart_policy:
        condition: any

  todo-api:
    deploy:
      restart_policy:
        condition: any

  todo-service:
    deploy:
      restart_policy:
        condition: any

  todo-worker:
    deploy:
      restart_policy:
        condition: any

  nats:
    deploy:
      restart_policy:
        condition: any

  centrifugo:
    deploy:
      restart_policy:
        condition: any

  temporal:
    deploy:
      restart_policy:
        condition: any

  db:
    deploy:
      restart_policy:
        condition: any

  minio:
    deploy:
      restart_policy:
        condition: any

  minio-console:
    deploy:
      restart_policy:
        condition: any

  loki:
    deploy:
      restart_policy:
        condition: any

  promtail:
    deploy:
      restart_policy:
        condition: any

  grafana:
    deploy:
      restart_policy:
        condition: any

  keycloak:
    build:
      context: ./backend/keycloak/docker
      dockerfile: Dockerfile.prod
    deploy:
      restart_policy:
        condition: any

secrets:
  private.key:
    file: ./env/private.key
  public.crt:
    file: ./env/public.crt

networks:
  todo-app:
    driver: overlay
    attachable: true
