version: "3.9"

services:
  caddy:
    build: ./backend/caddy/dev
    image: todo-app/caddy
    container_name: todo-app-caddy
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/caddy.env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - todo-app

  todo-app:
    build: ./frontend
    image: todo-app/todo-app
    container_name: todo-app
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-app.env
    networks:
      - todo-app

  todo-api:
    build: ./backend/todo-api
    image: todo-app/todo-api
    container_name: todo-app-todo-api
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-api.env
    networks:
      - todo-app
    depends_on:
      - db
      - nats-configure

  todo-service:
    build: ./backend/todo-service
    image: todo-app/todo-service
    container_name: todo-app-todo-service
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-service.env
    networks:
      - todo-app
    depends_on:
      - db
      - nats-configure

  todo-worker:
    build: ./backend/todo-worker
    image: todo-app/todo-worker
    container_name: todo-app-todo-worker
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/todo-worker.env
    networks:
      - todo-app
    depends_on:
      - db
      - temporal

  nats:
    build: ./backend/nats
    image: todo-app/nats
    container_name: todo-app-nats
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/nats.env
    ports:
      - 4222:4222
    volumes:
      - nats:/nats
    networks:
      - todo-app

  nats-configure:
    build: ./backend/nats-configure
    image: todo-app/nats-configure
    container_name: todo-app-nats-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/nats-configure.env
    networks:
      - todo-app
    depends_on:
      - nats

  centrifugo:
    image: centrifugo/centrifugo
    container_name: todo-app-centrifugo
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/centrifugo.env
    ports:
      - 8000:8000
    networks:
      - todo-app
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  temporal:
    build: ./backend/temporal
    image: todo-app/temporal
    container_name: todo-app-temporal
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/temporal.env
    ports:
      - 7233:7233
    networks:
      - todo-app
    depends_on:
      - db

  db:
    build: ./backend/db/postgres
    image: todo-app/db
    container_name: todo-app-db
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - todo-app

  db-migrate:
    build: ./backend/db/migrate
    image: todo-app/db-migrate
    container_name: todo-app-db-migrate
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/migrate.env
    networks:
      - todo-app
    depends_on:
      - db

  minio:
    image: minio/minio
    container_name: todo-app-minio
    deploy:
      restart_policy:
        condition: on-failure
    command: server /data
    env_file:
      - ./env/minio.env
    volumes:
      - minio:/data
    networks:
      - todo-app

  minio-console:
    image: minio/console
    container_name: todo-app-minio-console
    deploy:
      restart_policy:
        condition: on-failure
    command: server
    env_file:
      - ./env/minio-console.env
    networks:
      - todo-app
    depends_on:
      - minio

  minio-migrate:
    build: ./monitor/minio/migrate
    image: todo-app/minio-migrate
    container_name: todo-app-minio-migrate
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/minio.env
      - ./env/minio-migrate.env
    networks:
      - todo-app
    depends_on:
      - minio

  loki:
    build: ./monitor/loki
    image: todo-app/loki
    container_name: todo-app-loki
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/minio.env
      - ./env/loki.env
    networks:
      - todo-app
    depends_on:
      - minio

  promtail:
    build: ./monitor/promtail
    image: todo-app/promtail
    container_name: todo-app-promtail
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/promtail.env
    volumes:
      - promtail:/tmp/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - todo-app
    depends_on:
      - loki

  grafana:
    build: ./monitor/grafana/docker
    image: todo-app/grafana
    container_name: todo-app-grafana
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/grafana.env
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - todo-app
    depends_on:
      - db
      - loki

  grafana-configure:
    build: ./monitor/grafana/configure
    image: todo-app/grafana-configure
    container_name: todo-app-grafana-configure
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/grafana-configure.env
    networks:
      - todo-app
    depends_on:
      - grafana

  keycloak:
    build:
      context: ./backend/keycloak/docker
      dockerfile: Dockerfile
    image: todo-app/keycloak
    container_name: todo-app-keycloak
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/keycloak.env
    networks:
      - todo-app
    depends_on:
      - db

networks:
  todo-app:
    name: todo-app

volumes:
  db:
  nats:
  minio:
  grafana:
  promtail:
  caddy_data:
  caddy_config:
