services:
  caddy:
    build: ./backend/caddy/prod
    deploy:
      restart_policy:
        condition: any
    ports:
      - 443:443

  todo-app:
    deploy:
      restart_policy:
        condition: any

  todo-api:
    deploy:
      restart_policy:
        condition: any

  todo-service:
    deploy:
      restart_policy:
        condition: any

  todo-worker:
    deploy:
      restart_policy:
        condition: any

  nats:
    deploy:
      restart_policy:
        condition: any

  centrifugo:
    deploy:
      restart_policy:
        condition: any

  temporal:
    deploy:
      restart_policy:
        condition: any

  db:
    deploy:
      restart_policy:
        condition: any

  minio:
    deploy:
      restart_policy:
        condition: any

  loki:
    deploy:
      restart_policy:
        condition: any

  alloy:
    deploy:
      restart_policy:
        condition: any

  grafana:
    deploy:
      restart_policy:
        condition: any

  keycloak:
    build:
      context: ./backend/keycloak/docker
      dockerfile: Dockerfile.prod
    deploy:
      restart_policy:
        condition: any

networks:
  todo-app:
    name: todo-app
    driver: overlay
    attachable: true
