apiVersion: 1

datasources:
  - name: postgres
    uid: postgres
    type: postgres
    access: proxy
    url: ${PG_URL}
    user: ${PG_USER}
    jsonData:
      database: ${PG_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${PG_PASSWORD}

  - name: loki
    uid: loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
